from google import genai
from google.genai import types
from tenacity import retry, wait_random_exponential
from config import PROJECT_ID, MODEL_NAME
from utils import get_current_date

client = genai.Client(
    vertexai=True,
    project=PROJECT_ID,
    location='global',
)

expense_schema = {
    "type": "OBJECT",
    "properties": {
        "currency": {"type": "STRING"},
        "price": {"type": "NUMBER"},
        "category": {"type": "STRING"},
        "description": {"type": "STRING"},
        "date": {"type": "STRING"},
    },
}

expense_config = types.GenerateContentConfig(
    temperature=0.2,
    response_mime_type="application/json",
    response_schema=expense_schema,
)

# function to call gemini to process expense text
# implement exponential backoff for load handling
@retry(wait=wait_random_exponential(multiplier=1, max=60))
async def process_expense_text(input_text: str, preferred_currency: str = "GBP", existing_categories: list = None, category_rules: list = None):
    """parses expense details from plain text input
    Args:
        input_text (str) : user input
        preferred_currency (str) : user's preferred currency. Defaults to GBP
        existing_categories (list) : list of categories the user has used before
        category_rules (list) : list of keyword-to-category rules set by the user
    Returns:
        response.text (str) : text generated by LLM with json structure
    """

    today, day = get_current_date()

    category_instruction = "CATEGORY (think about what it should be based on the item or place provided. Keep to 1 word if possible);"
    if existing_categories:
        category_instruction = (
            f"CATEGORY (the user's existing categories are: {existing_categories}. "
            "Use one of these if applicable. Only create a new category if none of the existing ones fit. Keep to 1 word if possible);"
        )

    rule_instruction = ""
    if category_rules:
        rules_formatted = ", ".join([f"'{r['keyword']}' -> {r['category']}" for r in category_rules])
        rule_instruction = (
            f"\n    CATEGORY RULES: The user has set these category preferences: [{rules_formatted}]. "
            "If the expense description matches any of these keywords, you MUST use the corresponding category."
        )

    prompt = f"""
    Extract structured expense details from this text: {input_text}.

    Today's date is {today}. Today is {day}. Infer the expense date based on today's date.

    Important instructions for each field:
    CURRENCY (the user's currency is {preferred_currency}. ALWAYS use this currency unless the user explicitly specifies a different currency code or symbol in their input. Assume that $ is SGD, not USD. Make sure to return only the 3-letter symbol (example: GBP, SGD, EUR, JPY, MYR, RMB));
    {category_instruction}
    DESCRIPTION (this can just be the place or store name, if specified. If a shop name is not specified or is unclear, be more detailed in the description,
    but make sure to only include whatever is already in the user input.);
    DATE (be extra careful if the user inputs terms like "last Tuesday" or "last Monday". Count backwards carefully to find the exact date from today's date).
    {rule_instruction}
    """
    response = await client.aio.models.generate_content(
        model=MODEL_NAME, contents=prompt, config=expense_config
    )
    return response.text

# function to call gemini to process expense (e.g. receipt) image
# implement exponential backoff for load handling
@retry(wait=wait_random_exponential(multiplier=1, max=60))
async def process_expense_image(image_path: str, caption: str="", preferred_currency: str = "GBP", existing_categories: list = None, category_rules: list = None):
    """parses expense details from image input
    Args:
        - image_path (str) : path to image sent by user
        - caption (str) : caption accompanying image for further instructions. Defaults to None
        - preferred_currency (str) : user's preferred currency. Defaults to GBP
        - existing_categories (list) : list of categories the user has used before
        - category_rules (list) : list of keyword-to-category rules set by the user
    Returns:
        response.text (str): text generated by LLM with json structure
    """

    today, day = get_current_date()

    category_instruction = "For category, determine a suitable category based on the vendor or purchased items."
    if existing_categories:
        category_instruction = (
            f"For category, the user's existing categories are: {existing_categories}. "
            "Use one of these if applicable. Only create a new category if none of the existing ones fit."
        )

    rule_instruction = ""
    if category_rules:
        rules_formatted = ", ".join([f"'{r['keyword']}' -> {r['category']}" for r in category_rules])
        rule_instruction = (
            f"\n    - CATEGORY RULES: The user has set these category preferences: [{rules_formatted}]. "
            "If the expense description matches any of these keywords, you MUST use the corresponding category."
        )

    prompt = f"""
    Extract structured expense details from the image and provided image caption.

    IMPORTANT - Image caption: {caption or "No caption provided"}

    Use the caption as an additional source of information when determining expense details.

    Instructions:
    - Look for the TOTAL amount (usually near the bottom, labeled as "TOTAL", "GRAND TOTAL", "AMOUNT DUE", etc.).
    - Today's date is {today}. Today is {day}. Extrapolate the expense date based on today's date.
    - Use receipt date if available; otherwise, infer a reasonable date based on context.
    - Be extra careful if the user inputs terms like "last Tuesday" or "last Monday". Count backwards carefully to find the exact date from today's date.
    - The user's currency is {preferred_currency}. ALWAYS use this currency unless the user explicitly specifies a different currency code or symbol in their input, or the receipt clearly shows a different currency. Assume $ means SGD unless context suggests otherwise.
    - Make sure to return only the 3-letter symbol (example: GBP, SGD, EUR, JPY, MYR, RMB).
    - For description, use the store/vendor name or a summary of the main purchase.
    - {category_instruction}
    {rule_instruction}
    """

    with open(image_path, "rb") as img_file:
        image_bytes = img_file.read()

    # Detect MIME type from magic bytes instead of assuming PNG
    if image_bytes[:3] == b'\xff\xd8\xff':
        mime_type = "image/jpeg"
    elif image_bytes[:4] == b'\x89PNG':
        mime_type = "image/png"
    elif image_bytes[:4] == b'RIFF' and image_bytes[8:12] == b'WEBP':
        mime_type = "image/webp"
    else:
        mime_type = "image/jpeg"  # fallback — most common from Telegram

    image_part = types.Part.from_bytes(
        mime_type=mime_type,
        data=image_bytes,
    )

    response = await client.aio.models.generate_content(
        model=MODEL_NAME, contents=[image_part, prompt], config=expense_config
    )
    return response.text

# function to refine extracted expense details
# implement exponential backoff for load handling
@retry(wait=wait_random_exponential(multiplier=1, max=60))
async def refine_expense_details(original_details, user_feedback):
    """Refines the parsed expense details based on user corrections.
    Args:
        - original_details (dict) : originally parsed expense details in json format
        - user_feedback (str) : user-provided feedback for requested changes
    Returns:
        - response.text (str) : text generated by LLM with json structure
    """
    prompt = f"""
    Here are the originally parsed expense details:
    {original_details}
    
    The user has provided the following feedback for correction:
    {user_feedback}
    
    Please refine the expense details accordingly while keeping other details unchanged.
    """
    response = await client.aio.models.generate_content(
        model=MODEL_NAME, contents=prompt, config=expense_config
    )
    return response.text
